# Generated by Django 3.0.8 on 2021-01-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_category', models.CharField(max_length=75)),
                ('item_price', models.CharField(max_length=50)),
            ],
        ),
    ]
