# Generated by Django 3.0.8 on 2021-01-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='', upload_to='items/'),
        ),
    ]
