# Generated by Django 3.0.8 on 2021-01-04 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('designApp', '0003_item_item_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
