# Generated by Django 3.0.8 on 2021-01-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designApp', '0006_auto_20210104_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
