# Generated by Django 3.0.8 on 2021-01-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designApp', '0009_item_item_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_category',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
