# Generated by Django 3.0.8 on 2021-01-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designApp', '0010_auto_20210106_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_desc',
            field=models.CharField(default='', max_length=500),
        ),
    ]
