# Generated by Django 3.0.8 on 2021-01-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designApp', '0011_auto_20210106_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_category',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
