# Generated by Django 3.0.8 on 2021-01-08 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('designApp', '0012_auto_20210106_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='system',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=70)),
                ('system_category', models.CharField(blank=True, max_length=150)),
                ('system_desc', models.CharField(max_length=500)),
                ('system_feature', models.CharField(max_length=200)),
                ('system_image1', models.ImageField(upload_to='systems/')),
                ('system_image2', models.ImageField(upload_to='systems/')),
                ('system_price', models.CharField(max_length=50)),
                ('system_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
