# Generated by Django 3.0.8 on 2021-01-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designApp', '0013_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='system_feature',
            field=models.CharField(max_length=350),
        ),
    ]
