# Generated by Django 3.0.8 on 2021-01-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designApp', '0014_auto_20210108_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='system_image1',
            field=models.ImageField(blank=True, upload_to='systems/'),
        ),
        migrations.AlterField(
            model_name='system',
            name='system_image2',
            field=models.ImageField(blank=True, upload_to='systems/'),
        ),
    ]
