# Generated by Django 3.0.8 on 2021-01-09 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('designApp', '0015_auto_20210109_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=30)),
                ('contact_email', models.CharField(max_length=50)),
                ('contact_message', models.CharField(max_length=500)),
                ('contact_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
